// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.um.canario.models;

import com.um.canario.models.Following;
import com.um.canario.models.FollowingDataOnDemand;
import com.um.canario.models.Tweeter;
import com.um.canario.models.TweeterDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect FollowingDataOnDemand_Roo_DataOnDemand {
    
    declare @type: FollowingDataOnDemand: @Component;
    
    private Random FollowingDataOnDemand.rnd = new SecureRandom();
    
    private List<Following> FollowingDataOnDemand.data;
    
    @Autowired
    private TweeterDataOnDemand FollowingDataOnDemand.tweeterDataOnDemand;
    
    public Following FollowingDataOnDemand.getNewTransientFollowing(int index) {
        Following obj = new Following();
        setFollowed(obj, index);
        setFollower(obj, index);
        return obj;
    }
    
    public void FollowingDataOnDemand.setFollowed(Following obj, int index) {
        Tweeter followed = tweeterDataOnDemand.getRandomTweeter();
        obj.setFollowed(followed);
    }
    
    public void FollowingDataOnDemand.setFollower(Following obj, int index) {
        Tweeter follower = tweeterDataOnDemand.getRandomTweeter();
        obj.setFollower(follower);
    }
    
    public Following FollowingDataOnDemand.getSpecificFollowing(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Following obj = data.get(index);
        Long id = obj.getId();
        return Following.findFollowing(id);
    }
    
    public Following FollowingDataOnDemand.getRandomFollowing() {
        init();
        Following obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Following.findFollowing(id);
    }
    
    public boolean FollowingDataOnDemand.modifyFollowing(Following obj) {
        return false;
    }
    
    public void FollowingDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Following.findFollowingEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Following' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Following>();
        for (int i = 0; i < 10; i++) {
            Following obj = getNewTransientFollowing(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
