// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.um.canario.models;

import com.um.canario.models.Hash;
import com.um.canario.models.HashDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect HashDataOnDemand_Roo_DataOnDemand {
    
    declare @type: HashDataOnDemand: @Component;
    
    private Random HashDataOnDemand.rnd = new SecureRandom();
    
    private List<Hash> HashDataOnDemand.data;
    
    public Hash HashDataOnDemand.getNewTransientHash(int index) {
        Hash obj = new Hash();
        setName(obj, index);
        return obj;
    }
    
    public void HashDataOnDemand.setName(Hash obj, int index) {
        String name = "name_" + index;
        obj.setName(name);
    }
    
    public Hash HashDataOnDemand.getSpecificHash(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Hash obj = data.get(index);
        Long id = obj.getId();
        return Hash.findHash(id);
    }
    
    public Hash HashDataOnDemand.getRandomHash() {
        init();
        Hash obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Hash.findHash(id);
    }
    
    public boolean HashDataOnDemand.modifyHash(Hash obj) {
        return false;
    }
    
    public void HashDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Hash.findHashEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Hash' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Hash>();
        for (int i = 0; i < 10; i++) {
            Hash obj = getNewTransientHash(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
