// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.um.canario.models;

import com.um.canario.models.HashIntegrationTest;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect HashIntegrationTest_Roo_Configurable {
    
    declare @type: HashIntegrationTest: @Configurable;
    
}
