// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.um.canario.models;

import com.um.canario.models.Hash;
import com.um.canario.models.HashDataOnDemand;
import com.um.canario.models.HashIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect HashIntegrationTest_Roo_IntegrationTest {
    
    declare @type: HashIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: HashIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: HashIntegrationTest: @Transactional;
    
    @Autowired
    private HashDataOnDemand HashIntegrationTest.dod;
    
    @Test
    public void HashIntegrationTest.testCountHashes() {
        Assert.assertNotNull("Data on demand for 'Hash' failed to initialize correctly", dod.getRandomHash());
        long count = Hash.countHashes();
        Assert.assertTrue("Counter for 'Hash' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void HashIntegrationTest.testFindHash() {
        Hash obj = dod.getRandomHash();
        Assert.assertNotNull("Data on demand for 'Hash' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Hash' failed to provide an identifier", id);
        obj = Hash.findHash(id);
        Assert.assertNotNull("Find method for 'Hash' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Hash' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void HashIntegrationTest.testFindAllHashes() {
        Assert.assertNotNull("Data on demand for 'Hash' failed to initialize correctly", dod.getRandomHash());
        long count = Hash.countHashes();
        Assert.assertTrue("Too expensive to perform a find all test for 'Hash', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Hash> result = Hash.findAllHashes();
        Assert.assertNotNull("Find all method for 'Hash' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Hash' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void HashIntegrationTest.testFindHashEntries() {
        Assert.assertNotNull("Data on demand for 'Hash' failed to initialize correctly", dod.getRandomHash());
        long count = Hash.countHashes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Hash> result = Hash.findHashEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Hash' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Hash' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void HashIntegrationTest.testFlush() {
        Hash obj = dod.getRandomHash();
        Assert.assertNotNull("Data on demand for 'Hash' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Hash' failed to provide an identifier", id);
        obj = Hash.findHash(id);
        Assert.assertNotNull("Find method for 'Hash' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyHash(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Hash' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void HashIntegrationTest.testMergeUpdate() {
        Hash obj = dod.getRandomHash();
        Assert.assertNotNull("Data on demand for 'Hash' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Hash' failed to provide an identifier", id);
        obj = Hash.findHash(id);
        boolean modified =  dod.modifyHash(obj);
        Integer currentVersion = obj.getVersion();
        Hash merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Hash' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void HashIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Hash' failed to initialize correctly", dod.getRandomHash());
        Hash obj = dod.getNewTransientHash(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Hash' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Hash' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Hash' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void HashIntegrationTest.testRemove() {
        Hash obj = dod.getRandomHash();
        Assert.assertNotNull("Data on demand for 'Hash' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Hash' failed to provide an identifier", id);
        obj = Hash.findHash(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Hash' with identifier '" + id + "'", Hash.findHash(id));
    }
    
}
