// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.um.canario.models;

import com.um.canario.models.HashMention;
import com.um.canario.models.HashMentionDataOnDemand;
import com.um.canario.models.HashMentionIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect HashMentionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: HashMentionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: HashMentionIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: HashMentionIntegrationTest: @Transactional;
    
    @Autowired
    private HashMentionDataOnDemand HashMentionIntegrationTest.dod;
    
    @Test
    public void HashMentionIntegrationTest.testCountHashMentions() {
        Assert.assertNotNull("Data on demand for 'HashMention' failed to initialize correctly", dod.getRandomHashMention());
        long count = HashMention.countHashMentions();
        Assert.assertTrue("Counter for 'HashMention' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void HashMentionIntegrationTest.testFindHashMention() {
        HashMention obj = dod.getRandomHashMention();
        Assert.assertNotNull("Data on demand for 'HashMention' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'HashMention' failed to provide an identifier", id);
        obj = HashMention.findHashMention(id);
        Assert.assertNotNull("Find method for 'HashMention' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'HashMention' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void HashMentionIntegrationTest.testFindAllHashMentions() {
        Assert.assertNotNull("Data on demand for 'HashMention' failed to initialize correctly", dod.getRandomHashMention());
        long count = HashMention.countHashMentions();
        Assert.assertTrue("Too expensive to perform a find all test for 'HashMention', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<HashMention> result = HashMention.findAllHashMentions();
        Assert.assertNotNull("Find all method for 'HashMention' illegally returned null", result);
        Assert.assertTrue("Find all method for 'HashMention' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void HashMentionIntegrationTest.testFindHashMentionEntries() {
        Assert.assertNotNull("Data on demand for 'HashMention' failed to initialize correctly", dod.getRandomHashMention());
        long count = HashMention.countHashMentions();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<HashMention> result = HashMention.findHashMentionEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'HashMention' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'HashMention' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void HashMentionIntegrationTest.testFlush() {
        HashMention obj = dod.getRandomHashMention();
        Assert.assertNotNull("Data on demand for 'HashMention' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'HashMention' failed to provide an identifier", id);
        obj = HashMention.findHashMention(id);
        Assert.assertNotNull("Find method for 'HashMention' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyHashMention(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'HashMention' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void HashMentionIntegrationTest.testMergeUpdate() {
        HashMention obj = dod.getRandomHashMention();
        Assert.assertNotNull("Data on demand for 'HashMention' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'HashMention' failed to provide an identifier", id);
        obj = HashMention.findHashMention(id);
        boolean modified =  dod.modifyHashMention(obj);
        Integer currentVersion = obj.getVersion();
        HashMention merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'HashMention' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void HashMentionIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'HashMention' failed to initialize correctly", dod.getRandomHashMention());
        HashMention obj = dod.getNewTransientHashMention(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'HashMention' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'HashMention' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'HashMention' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void HashMentionIntegrationTest.testRemove() {
        HashMention obj = dod.getRandomHashMention();
        Assert.assertNotNull("Data on demand for 'HashMention' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'HashMention' failed to provide an identifier", id);
        obj = HashMention.findHashMention(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'HashMention' with identifier '" + id + "'", HashMention.findHashMention(id));
    }
    
}
