// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.um.canario.models;

import com.um.canario.models.Mention;
import com.um.canario.models.MentionDataOnDemand;
import com.um.canario.models.MentionIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MentionIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MentionIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MentionIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: MentionIntegrationTest: @Transactional;
    
    @Autowired
    private MentionDataOnDemand MentionIntegrationTest.dod;
    
    @Test
    public void MentionIntegrationTest.testCountMentions() {
        Assert.assertNotNull("Data on demand for 'Mention' failed to initialize correctly", dod.getRandomMention());
        long count = Mention.countMentions();
        Assert.assertTrue("Counter for 'Mention' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MentionIntegrationTest.testFindMention() {
        Mention obj = dod.getRandomMention();
        Assert.assertNotNull("Data on demand for 'Mention' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Mention' failed to provide an identifier", id);
        obj = Mention.findMention(id);
        Assert.assertNotNull("Find method for 'Mention' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Mention' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void MentionIntegrationTest.testFindAllMentions() {
        Assert.assertNotNull("Data on demand for 'Mention' failed to initialize correctly", dod.getRandomMention());
        long count = Mention.countMentions();
        Assert.assertTrue("Too expensive to perform a find all test for 'Mention', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Mention> result = Mention.findAllMentions();
        Assert.assertNotNull("Find all method for 'Mention' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Mention' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MentionIntegrationTest.testFindMentionEntries() {
        Assert.assertNotNull("Data on demand for 'Mention' failed to initialize correctly", dod.getRandomMention());
        long count = Mention.countMentions();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Mention> result = Mention.findMentionEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Mention' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Mention' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MentionIntegrationTest.testFlush() {
        Mention obj = dod.getRandomMention();
        Assert.assertNotNull("Data on demand for 'Mention' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Mention' failed to provide an identifier", id);
        obj = Mention.findMention(id);
        Assert.assertNotNull("Find method for 'Mention' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyMention(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Mention' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MentionIntegrationTest.testMergeUpdate() {
        Mention obj = dod.getRandomMention();
        Assert.assertNotNull("Data on demand for 'Mention' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Mention' failed to provide an identifier", id);
        obj = Mention.findMention(id);
        boolean modified =  dod.modifyMention(obj);
        Integer currentVersion = obj.getVersion();
        Mention merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Mention' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MentionIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Mention' failed to initialize correctly", dod.getRandomMention());
        Mention obj = dod.getNewTransientMention(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Mention' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Mention' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Mention' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void MentionIntegrationTest.testRemove() {
        Mention obj = dod.getRandomMention();
        Assert.assertNotNull("Data on demand for 'Mention' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Mention' failed to provide an identifier", id);
        obj = Mention.findMention(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Mention' with identifier '" + id + "'", Mention.findMention(id));
    }
    
}
