// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.um.canario.models;

import com.um.canario.models.Mention;
import com.um.canario.models.MentionDataOnDemand;
import com.um.canario.models.TweetDataOnDemand;
import com.um.canario.models.TweeterDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect MentionDataOnDemand_Roo_DataOnDemand {
    
    declare @type: MentionDataOnDemand: @Component;
    
    private Random MentionDataOnDemand.rnd = new SecureRandom();
    
    private List<Mention> MentionDataOnDemand.data;
    
    @Autowired
    private TweetDataOnDemand MentionDataOnDemand.tweetDataOnDemand;
    
    @Autowired
    private TweeterDataOnDemand MentionDataOnDemand.tweeterDataOnDemand;
    
    public Mention MentionDataOnDemand.getNewTransientMention(int index) {
        Mention obj = new Mention();
        return obj;
    }
    
    public Mention MentionDataOnDemand.getSpecificMention(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Mention obj = data.get(index);
        Long id = obj.getId();
        return Mention.findMention(id);
    }
    
    public Mention MentionDataOnDemand.getRandomMention() {
        init();
        Mention obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Mention.findMention(id);
    }
    
    public boolean MentionDataOnDemand.modifyMention(Mention obj) {
        return false;
    }
    
    public void MentionDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Mention.findMentionEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Mention' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Mention>();
        for (int i = 0; i < 10; i++) {
            Mention obj = getNewTransientMention(i);
            try {
                obj.persist();
            } catch (ConstraintViolationException e) {
                StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getConstraintDescriptor()).append(":").append(cv.getMessage()).append("=").append(cv.getInvalidValue()).append("]");
                }
                throw new RuntimeException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
