// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.um.canario.models;

import com.um.canario.models.Tweeter;
import com.um.canario.models.TweeterDataOnDemand;
import com.um.canario.models.TweeterIntegrationTest;
import java.util.List;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TweeterIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TweeterIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TweeterIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TweeterIntegrationTest: @Transactional;
    
    @Autowired
    private TweeterDataOnDemand TweeterIntegrationTest.dod;
    
    @Test
    public void TweeterIntegrationTest.testCountTweeters() {
        Assert.assertNotNull("Data on demand for 'Tweeter' failed to initialize correctly", dod.getRandomTweeter());
        long count = Tweeter.countTweeters();
        Assert.assertTrue("Counter for 'Tweeter' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TweeterIntegrationTest.testFindTweeter() {
        Tweeter obj = dod.getRandomTweeter();
        Assert.assertNotNull("Data on demand for 'Tweeter' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Tweeter' failed to provide an identifier", id);
        obj = Tweeter.findTweeter(id);
        Assert.assertNotNull("Find method for 'Tweeter' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Tweeter' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TweeterIntegrationTest.testFindAllTweeters() {
        Assert.assertNotNull("Data on demand for 'Tweeter' failed to initialize correctly", dod.getRandomTweeter());
        long count = Tweeter.countTweeters();
        Assert.assertTrue("Too expensive to perform a find all test for 'Tweeter', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Tweeter> result = Tweeter.findAllTweeters();
        Assert.assertNotNull("Find all method for 'Tweeter' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Tweeter' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TweeterIntegrationTest.testFindTweeterEntries() {
        Assert.assertNotNull("Data on demand for 'Tweeter' failed to initialize correctly", dod.getRandomTweeter());
        long count = Tweeter.countTweeters();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Tweeter> result = Tweeter.findTweeterEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Tweeter' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Tweeter' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TweeterIntegrationTest.testFlush() {
        Tweeter obj = dod.getRandomTweeter();
        Assert.assertNotNull("Data on demand for 'Tweeter' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Tweeter' failed to provide an identifier", id);
        obj = Tweeter.findTweeter(id);
        Assert.assertNotNull("Find method for 'Tweeter' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTweeter(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Tweeter' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TweeterIntegrationTest.testMergeUpdate() {
        Tweeter obj = dod.getRandomTweeter();
        Assert.assertNotNull("Data on demand for 'Tweeter' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Tweeter' failed to provide an identifier", id);
        obj = Tweeter.findTweeter(id);
        boolean modified =  dod.modifyTweeter(obj);
        Integer currentVersion = obj.getVersion();
        Tweeter merged = obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Tweeter' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TweeterIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Tweeter' failed to initialize correctly", dod.getRandomTweeter());
        Tweeter obj = dod.getNewTransientTweeter(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Tweeter' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Tweeter' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        Assert.assertNotNull("Expected 'Tweeter' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TweeterIntegrationTest.testRemove() {
        Tweeter obj = dod.getRandomTweeter();
        Assert.assertNotNull("Data on demand for 'Tweeter' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Tweeter' failed to provide an identifier", id);
        obj = Tweeter.findTweeter(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Tweeter' with identifier '" + id + "'", Tweeter.findTweeter(id));
    }
    
}
